[[redirects]]
  from = "/callback"
  to = "https://authrizon.netlify.app/chat"
  status = 200

  [[plugins]]
  package = "netlify-plugin-auth0-patch-urls"
  [build]
    functions = "functions"
    publish = "public/"
    command = "npm run start"
[dev]
  jwtSecret = "test"